name: makeWIKIPJA
on: workflow_dispatch
jobs:
  makeWIKIPJA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: sh -c ${{ github.workspace }}/makeWIKIPJA.sh
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            checkWIKIPJA-*.sh
            catWIKIPJA-*.sh
            EPWING-Wikipedia-JA-*.sha256.gz
            EPWING-Wikipedia-JA-*.tar.*
